name: Huerto.net
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#343434'
    - '#646464'
    - '#b6b6b6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
