name: Huerto.net
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171218'
    - '#e8eff7'
    - '#493f40'
    - '#b5c5dc'
    - '#8e7e88'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
